# Generated by Django 3.2.8 on 2021-10-16 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(default='', max_length=50)),
                ('code', models.CharField(db_index=True, default='', max_length=100)),
                ('name', models.CharField(db_index=True, default='', max_length=200)),
                ('description', models.TextField(null=True)),
                ('parent_code', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'code',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(default='', max_length=50)),
                ('title', models.CharField(db_index=True, default='', max_length=200)),
                ('director', models.CharField(db_index=True, default='', max_length=200)),
                ('release_date', models.DateTimeField()),
                ('poster_path', models.TextField(default='')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(default='', max_length=50)),
                ('email', models.CharField(db_index=True, default='', max_length=200)),
                ('name', models.CharField(default='', max_length=50)),
                ('age', models.IntegerField(db_index=True, default=0)),
                ('password', models.TextField(default='')),
                ('phone_no', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(default='', max_length=50)),
                ('movie', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, related_name='request', to='swe.movie')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='request', to='swe.user')),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='MovieMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(default='', max_length=50)),
                ('movie', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, related_name='movie_meta', to='swe.movie')),
                ('type_code', models.ForeignKey(db_column='type_code_id', on_delete=django.db.models.deletion.CASCADE, related_name='movie_meta', to='swe.code')),
            ],
            options={
                'db_table': 'movie_meta',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(default='', max_length=50)),
                ('movie', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='swe.movie')),
                ('request', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='swe.request')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='swe.user')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
