# Generated by Django 3.1.1 on 2021-10-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swe', '0002_auto_20211016_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
