# Generated by Django 3.1.1 on 2021-10-17 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swe', '0003_user_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(default='', max_length=50)),
                ('email', models.CharField(db_index=True, default='', max_length=200)),
                ('name', models.CharField(default='', max_length=50)),
                ('age', models.IntegerField(db_index=True, default=0)),
                ('access_token', models.CharField(blank=True, max_length=200)),
                ('password', models.TextField(default='')),
                ('phone_no', models.CharField(default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='swe.member'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='request', to='swe.member'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
