# Generated by Django 3.1.1 on 2021-10-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swe', '0004_auto_20211017_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='access_token',
            field=models.TextField(default=''),
        ),
    ]
