# Generated by Django 3.1.1 on 2021-10-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swe', '0005_auto_20211017_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='daily_view',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_view',
            field=models.IntegerField(default=0),
        ),
    ]
