# Generated by Django 3.1.1 on 2021-10-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swe', '0007_auto_20211024_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='parent_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
