# Generated by Django 3.1.1 on 2021-11-07 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swe', '0009_auto_20211106_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='request',
            field=models.ForeignKey(db_column='request_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='swe.request'),
        ),
    ]
