# Generated by Django 3.1.1 on 2021-11-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swe', '0010_auto_20211107_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='member',
            name='profession',
            field=models.CharField(default='', max_length=50),
        ),
    ]
