# Generated by Django 3.1.1 on 2021-12-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swe', '0011_auto_20211115_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
