# Generated by Django 3.1.1 on 2022-01-09 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swe', '0013_reopen'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default=True, null=True, upload_to='')),
                ('movie', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, related_name='movie_image_meta', to='swe.movie')),
            ],
            options={
                'db_table': 'movie_image',
            },
        ),
    ]
