# Generated by Django 3.1.1 on 2022-03-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swe', '0014_movieimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='access_token',
            new_name='refresh_token',
        ),
    ]
