# Generated by Django 4.1 on 2022-09-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swe', '0002_rename_creation_date_code_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieimage',
            old_name='image',
            new_name='url',
        ),
    ]
