# Generated by Django 4.1 on 2022-09-07 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swe', '0003_rename_image_movieimage_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(db_index=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='MovieGenreAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('genre', models.ForeignKey(db_column='genre_id', on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='swe.genre')),
            ],
            options={
                'db_table': 'movie_genre_assoc',
            },
        ),
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='MovieMeta',
        ),
        migrations.AddField(
            model_name='moviegenreassoc',
            name='movie',
            field=models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='swe.movie'),
        ),
    ]
