# Generated by Django 4.1 on 2022-09-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swe', '0005_user_alter_comment_user_alter_request_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
