# Generated by Django 4.1 on 2022-09-11 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swe', '0006_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('email', models.CharField(db_index=True, default='', max_length=200)),
                ('profession', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('address', models.TextField(default='')),
                ('age', models.IntegerField(db_index=True, default=0)),
                ('sex', models.CharField(default='', max_length=10)),
                ('refresh_token', models.TextField(default='')),
                ('password', models.TextField(default='')),
                ('phone_no', models.CharField(default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='comment',
            name='member',
            field=models.ForeignKey(db_column='member_id', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='swe.member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='member',
            field=models.ForeignKey(db_column='member_id', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='swe.member'),
            preserve_default=False,
        ),
    ]
