# Generated by Django 4.1 on 2022-09-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swe', '0008_userprofile_remove_comment_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=100)),
            ],
        ),
    ]
